name: Check README

on:
  push:
    branches:
      - main

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if README exists
        run: |
          if [ -f README.md ]; then
            echo "README.md exists"
          else
            echo "README.md does not exist"
            exit 1
          fi
